---
- name: install plank - add plank ppa
  apt_repository:
    repo: 'ppa:ricotz/docky'
    state: present
    update_cache: yes
  sudo: yes

- name: install plank
  apt:
    name: plank
    update_cache: yes
  sudo: yes

- name: install plank - Make sure that the autostart directory exsists
  file:
    path: "/home/{{ username }}/.config/autostart"
    state: directory

- name: install plank - Make Plank autostart
  copy:
    src: plank.desktop
    dest: "/home/{{ username }}/.config/autostart/plank.desktop"
    mode: 0755

- name: gnome-terminal launcher-hide-mode
  dconf:
    key: /org/compiz/profiles/unity/plugins/unityshell/launcher-hide-mode
    int: 1
