---
- name: download vagrant .deb package
  get_url:
    url: "{{ vagrant_url }}"
    dest: "{{ ansible_env.HOME }}/setup/vagrant.deb"
    mode: 0755

- name: get currently installed vagrant version
  command: "vagrant --version"
  sudo: yes
  register: result
  ignore_errors: True
  always_run: True

- name: install vagrant
  apt:
    deb: "{{ ansible_env.HOME }}/setup/vagrant.deb"
  sudo: yes
  when: "result.rc !=0 or 'A later version is already installed' in result.stderr"

- name: download virtualbox .deb package
  get_url:
    url: "{{ virtualbox_url }}"
    dest: "{{ ansible_env.HOME }}/setup/virtualbox.deb"
    mode: 0755

- name: get currently installed virtualbox version
  command: "vboxmanage --version"
  sudo: yes
  register: result
  ignore_errors: True
  always_run: True

- name: install virtualbox
  apt:
    deb: "{{ ansible_env.HOME }}/setup/virtualbox.deb"
  sudo: yes
  when: "result.rc !=0"

- name: install wave dependencies
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - python-pip
    - curl
    - nfs-kernel-server
    - nfs-common
    - rpcbind
    - tmux
    - npm
    - libjpeg-dev
    - libfreetype6-dev
    - zlib1g-dev
    - libpng12-dev
    - python-dev
    - libpq-dev
    - python-dev
  sudo: yes

- name: download nvm source
  git:
    repo: "https://github.com/creationix/nvm.git"
    dest: "{{ ansible_env.HOME }}/setup/.nvm"
    version: v0.26.1
  tags: nodejs

- name: install node with nvm
  shell: "source {{ ansible_env.HOME }}/setup/.nvm/nvm.sh && nvm install 5.3.0 && nvm alias default v5.3.0"
  args:
    chdir: "{{ ansible_env.HOME }}/setup/.nvm"
    executable: /bin/bash
  tags: nodejs

- name: download npm installer
  get_url:
    url: https://www.npmjs.com/install.sh
    dest: /tmp/npm-install.sh
    validate_certs: false
  tags: nodejs

- name: install npm
  shell: "source {{ ansible_env.HOME }}/setup/.nvm/nvm.sh && source /tmp/npm-install.sh"
  args:
    chdir: "{{ ansible_env.HOME }}/setup/.nvm"
    executable: /bin/bash
  tags: nodejs

- name: install global nodejs packages
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version|default('') }}"
    state: present
    global: yes
  tags: nodejs
  with_items:
    - {name: 'bower'}
    - {name: 'coffee-script', version: '1.7.1'}
    - {name: 'grunt-cli'}
    - {name: 'less'}
    - {name: 'jshint'}
    - {name: 'coffee-jshint'}
    - {name: 'localtunnel'}

- name: install tmuxp
  pip:
    name: tmuxp
  sudo: yes

- name: copy tmuxp config
  copy:
    src: .tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0755

- name: install ipython
  pip:
    name: ipython
  sudo: yes
